### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by novjan** [supervisorphp/configuration#18]
Hi,
please can you update dependencies of this package?

It is hard to use these days and I don't see any replacement for this package.

Thank you.

**Comment by sagikazarmark** [comment]
@novjan PRs are welcome, unfortunately I don't really have time to maintain this project anymore.

**Comment by enricog84** [comment]
@sagikazarmark 
Added a PR that updates the dependency on symfony/options-resolver. Should make it installable with newer Symfony versions again. I think the other required dependencies are still fine.
