### ISSUE TITLE
Byte options in INI files cannot be parsed with updated options-resolver

### ISSUE THREAD

**Issue by Flynamic** [supervisorphp/configuration#20]
I updated my composer dependencies, and am since getting this error:

`The option "logfile_maxbytes" with value "50MB" is expected to be of type "byte", but is of type "string"`,
in `/vendor/symfony/options-resolver/OptionsResolver.php:1030`. My `symfony/options-resolver` version is v5.2.1.

Removing `logfile_maxbytes` from my supervisord.conf obviously solves this problem for now.

It seems that since https://github.com/symfony/options-resolver/commit/cba9d944fa9262578f8c5287803895e5107dd34c, the `logfile_maxbytes` option can no longer be parsed because `is_<type>`, or in this case `is_byte`, is not called anymore.

**Comment by DracoWhitefire** [comment]
Should be resolved in https://github.com/supervisorphp/configuration/pull/22
